# Generated by Django 5.2.7 on 2025-10-07 11:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='Enter a short, descriptive title for the to-do item.', max_length=200)),
                ('body', models.TextField(help_text='Provide details or notes related to this to-do item.')),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
                'ordering': ['title'],
            },
        ),
    ]
